### ISSUE TITLE
Django 1.7, Python 3.4 ImportError: cannot import name 'smart_unicode'

### ISSUE THREAD

**Issue by pavlov99** [dstufft/django-passwords#16]
Hello everybody!

I use python 3.4 and django 1.7. Library version is 0.3.1, installed from repository: git+git://github.com/dstufft/django-passwords.git@v0.3.1

This version raises `ImportError`: during

    from passwords.fields import PasswordField
    ...
    from passwords.validators import validate_length, common_sequences, dictionary_words, complexity
    ...
    from django.utils.encoding import smart_unicode
    ImportError: cannot import name 'smart_unicode'

Thats because `smart_unicode` is supported only for python2: https://docs.djangoproject.com/en/1.7/ref/utils/#django.utils.encoding.smart_unicode

**Comment by maccesch** [comment]
Which file does rise this ImportError?

**Comment by pavlov99** [comment]
@maccesch , it is "passwords/fields.py".

As I checked, problem is with my version of django-passwords, it is 0.2.0 actually. For some reason pip failed to update the package. Following command tells that package is up to date.

    $ pip install --upgrade django-passwords
    Requirement already up-to-date: django-passwords in ./.env/lib/python3.4/site-packages

However it is not: pip could not find correct distribution.

    $ pip install django-passwords==0.3.2
    Collecting django-passwords==0.3.2
        Could not find a version that satisfies the requirement django-passwords==0.3.2 (from versions: 0.2.0)
        No matching distribution found for django-passwords==0.3.2

Package reinstall solved the problem. I used v0.3.2 tag from this repository.

    pip install git+git://github.com/dstufft/django-passwords.git@v0.3.2

Anyway, thanks for quick response!

**Comment by darwin1112** [comment]
安装pip install git+git://github.com/dstufft/django-passwords.git@v0.3.2
并没有解决以上错误

**Comment by maccesch** [comment]
@darwin1112 Sorry I don't understand :)

**Comment by y2030** [comment]
he said :
when he pip install git+git://github.com/dstufft/django-passwords.git@v0.3.2
still had the same error

**Comment by maccesch** [comment]
Thanks. Do you have the same error?
