### ISSUE TITLE
Issue with pypi

### ISSUE THREAD

**Issue by atabary** [dstufft/django-passwords#21]
There is a problem with the django-passwords package hosted on pypi : pypi lists [django-passwords 0.3.2](https://pypi.python.org/pypi/django-passwords) as being the most recent release, but in fact it is not possible to pip install it.

```bash
$ pip install django-passwords==0.3.2
Collecting django-passwords==0.3.2
  Could not find a version that satisfies the requirement django-passwords==0.3.2 (from versions: 0.2.0)
No matching distribution found for django-passwords==0.3.2
```

**Comment by maccesch** [comment]
ok latest version is now 0.3.3 and should be working
