### ISSUE TITLE
Combine punctuation with special characters

### ISSUE THREAD

**Issue by vstoykov** [dstufft/django-passwords#37]
When I configure complexity to require at least one special character and enter some of `#$@^` it does not recognize them as special and still give me a `ValidationError`.

When I see which are punctuation characters in Python I see list of not only punctuation but also special characters.

    >>> import string
    >>> string.punctuation
    '!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

I think that from the user perspective all of this are special characters. For punctuation most people thing of only `.,!?:;`, also in all form validation that I've seen they consider special character everything which is not a letter or number.

What you think about combining them together?

**Comment by maccesch** [comment]
Yes, you're right. Combining them makes perfectly sense. Would you mind creating a pull request for this?

**Comment by vstoykov** [comment]
Yes I will

**Comment by vstoykov** [comment]
#38 Is ready and waiting :)
