### ISSUE TITLE
Documentation pypi versus github

### ISSUE THREAD

**Issue by resalisbury** [dstufft/django-passwords#41]
The documentation on github does not match the documentation for the latest package 0.3.4 (specifically regarding the consolidation of PUNCTUATION and SPECIAL), which can lead to some surprising errors :)  I couldn't figure out why the validator wasn't validating my "special" character.  Perhaps could have a warning telling users to refer to documentation on pypi, if they install with pip.

**Comment by maccesch** [comment]
You're absolutely right. I updated the version on pypi. Its now 0.3.5
