### ISSUE TITLE
A typo in default COMMON_SEQUENCES

### ISSUE THREAD

**Issue by matiascelasco** [dstufft/django-passwords#8]
In validators.py file, there is a typo for common sequences based on "qwerty" keyboards.

COMMON_SEQUENCES = [
    "0123456789",
    "`1234567890-=",
    "~!@#$%^&*()_+",
    "abcdefghijklmnopqrstuvwxyz",
    "quertyuiop[]\\asdfghjkl;\'zxcvbnm,./",
    'quertyuiop{}|asdfghjkl;"zxcvbnm<>?',
    "quertyuiopasdfghjklzxcvbnm",
    "1qaz2wsx3edc4rfv5tgb6yhn7ujm8ik,9ol.0p;/-['=]\\",
    "qazwsxedcrfvtgbyhnujmikolp"
]

should be like this

COMMON_SEQUENCES = [
    (...)
    "qwertyuiop[]\\asdfghjkl;\'zxcvbnm,./",
    'qwertyuiop{}|asdfghjkl;"zxcvbnm<>?',
    "qwertyuiopasdfghjklzxcvbnm",
    (...)
]

**Comment by maccesch** [comment]
I'm sorry, I really tried, but I just can't find any differences in the two. Could you please highlight them?

**Comment by matiascelasco** [comment]
it should say "qwerty" instead of "querty"

**Comment by matiascelasco** [comment]
I just saw you added the "qwerty" ones but keeped the "querty" ones too

**Comment by maccesch** [comment]
haha, you're absolutely right! How didn't I see that?!
